------------------------------    Customers Analysis ------
   --- Who are the top 10 customers who generated the most revenue
SELECT c.customer_id, c.customer_name,
    SUM(s.net_sales) AS total_revenue
FROM customerss c
JOIN sales s ON c.customer_id = s.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC
LIMIT 10;
----------------  Which customers have placed the most orders
Select C.customer_id, C.customer_name, count(S.sale_id) as Total_order
        from customerss C
join sales S on C.customer_id = S.customer_id
group by C.customer_id, C.customer_name
order by Total_order desc
limit 10;
-------------------- How much did each customer purchase on average
select C.customer_id, C.customer_name,
    ROUND(AVG(S.net_sales), 2) AS Average_Purchase
FROM customerss C
JOIN sales S ON C.customer_id = S.customer_id
group BY C.customer_id, C.customer_name
ORDER BY Average_Purchase DESC;
------------ Which customer has not made any purchase
SELECT C.customer_id, C.customer_name
FROM customerss C
LEFT JOIN sales S ON C.customer_id = S.customer_id
WHERE S.sale_id IS NULL;
-------- How much total revenue was generated by customer segment
SELECT C.customer_segment, SUM(S.net_sales) AS Total_Revenue
FROM customerss C
JOIN sales S ON C.customer_id = S.customer_id
GROUP BY C.customer_segment
ORDER BY Total_Revenue DESC;
---------------- Which city generated the highest sales revenue
SELECT C.city, SUM(S.net_sales) AS Total_Revenue
FROM customerss C
JOIN sales S ON C.customer_id = S.customer_id
GROUP BY C.city
ORDER BY Total_Revenue DESC;
---- Which customers have made a total purchase of more than ₹2,00,000
select C.customer_id, C.customer_name, SUM(S.net_sales) AS Total_Purchase
FROM customerss C
JOIN sales S ON C.customer_id = S.customer_id
GROUP BY C.customer_id, C.customer_name
having sum(S.net_sales) > 200000
ORDER BY Total_Purchase DESC;
----------- Rank each customer based on total revenueS
SELECT C.customer_id, C.customer_name,
    SUM(S.net_sales) AS total_revenue,
    RANK() OVER (ORDER BY SUM(S.net_sales) DESC) AS revenue_rank 
FROM customerss C
JOIN sales S ON C.customer_id = S.customer_id
GROUP BY C.customer_id, C.customer_name
ORDER BY revenue_rank;
